---
title: "Advanced dimension reduction methods (including Principal Curves and surfaces, Independent Component Analysis, Non-negative Matrix Factorization)"
output: html_notebook
---

# Introduction

```{r}
library(dplyr)
library(ggplot2)
library(plotly)

library(analogue) # Principal Curves wrapper
library(fastICA)
library(NMF)

data("iris")
```

# Principal Curves

## Fitting principal curves
```{r}
# https://fromthebottomoftheheap.net/2014/01/09/pcurve-part-2/

x <- iris[1:4]
y <- iris[5]

results_iris_pc <- prcurve(x, maxit = 100)
results_iris_pc
```

## Results in 2D
```{r}
results_iris_pc_s <- data.frame(results_iris_pc$s[results_iris_pc$tag, ])
results_iris_pc_s['y'] <- y

ggplot() + 
  geom_line(data = results_iris_pc_s, mapping = aes(x = Petal.Length, y = Petal.Width)) +
  geom_point(data = iris, mapping = aes(x = Petal.Length, y = Petal.Width, color = Species))
```

## Results in 3D
```{r}
fig <- iris %>% 
  mutate(color = case_when(
    Species == 'setosa' ~ 'red',
    Species == 'virginica' ~ 'green',
    Species == 'versicolor' ~ 'blue'
  )) %>% 
  plot_ly(
    x = ~Sepal.Length,
    y = ~Sepal.Width,
    z = ~Petal.Width,
    type = 'scatter3d',
    mode = 'markers',
    marker = list(size = 1, color = ~color)
  ) 


results_iris_pc_smooth_curve <- results_iris_pc_s %>% mutate(color = 'black')
fig <- fig %>% 
  add_trace(
    data = results_iris_pc_smooth_curve,
    x = ~Sepal.Length,
    y = ~Sepal.Width,
    z = ~Petal.Width,
    type = 'scatter3d',
    mode = 'lines'
  )

fig
```

## Results in Principal Space
```{r}
plot(results_iris_pc)
```


```{r}
# Fitted line in PC dimension
iris_s_pc <- predict(results_iris_pc$ordination, results_iris_pc$s, type = "wa", scaling = 0)[, 1:2] %>% as.data.frame()

iris_pc <- predict(results_iris_pc$ordination, x, type = "wa", scaling = 0)[, 1:2] %>% as.data.frame()
iris_pc['y'] <- y

fig <- ggplot() +
  geom_line(data = iris_s_pc, mapping = aes(x = PC1, y = PC2)) +
  geom_point(data = iris_pc,  mapping = aes(x = PC1, y = PC2, color=y))

fig
```


```{r}
x_new <- sample_n(x, size = 20)
# New date into PC space
s_new <- predict(results_iris_pc, x_new) # New data on curve
s_new_pc_space <- predict(results_iris_pc$ordination, s_new, type = "wa", scaling = 0)[, 1:2] %>% as.data.frame()# From curve to PC space

fig +
  geom_point(data = s_new_pc_space, mapping = aes(x = PC1, y = PC2))
```

# Principal Surface




# ICA

## Simple example
```{r}
# http://rstudio-pubs-static.s3.amazonaws.com/93614_be30df613b2a4707b3e5a1a62f631d19.html
# https://rdrr.io/cran/fastICA/man/fastICA.html

# Source matrix
S <- cbind(sin((1:1000)/20), rep((((1:200)-100)/100), 5))
# Mixing matrix
A <- matrix(c(0.29, 0.655, -0.543, 0.557), 2, 2)
# plot graphs
par(mfcol = c(1, 2))
plot(1:1000, S[,1], type = "l",xlab = "S1", ylab = "")
plot(1:1000, S[,2], type = "l", xlab = "S2", ylab = "")
```

```{r}
# Mixed two signals
X <- S %*% A

par(mfcol = c(1, 2))
plot(1:1000, X[,1], type = "l",xlab = "X1", ylab = "")
plot(1:1000, X[,2], type = "l", xlab = "X2", ylab = "")
```

```{r}
# ICA for extracting independent sources from mixed signals
a <- fastICA(X, 2, alg.typ = "parallel", fun = "logcosh", alpha = 1,
             method = "R", row.norm = FALSE, maxit = 200,
             tol = 0.0001, verbose = FALSE)

par(mfcol = c(1, 2))
plot(1:1000, a$S[,1], type = "l", xlab = "S'1", ylab = "")
plot(1:1000, a$S[,2], type = "l", xlab = "S'2", ylab = "")
```

```{r}
par(mfcol = c(2, 3))
plot(1:1000, S[,1 ], type = "l", main = "Original Signals", 
     xlab = "", ylab = "")
plot(1:1000, S[,2 ], type = "l", xlab = "", ylab = "")
plot(1:1000, X[,1 ], type = "l", main = "Mixed Signals", 
     xlab = "", ylab = "")
plot(1:1000, X[,2 ], type = "l", xlab = "", ylab = "")
plot(1:1000, a$S[,1 ], type = "l", main = "ICA source estimates", 
     xlab = "", ylab = "")
plot(1:1000, a$S[, 2], type = "l", xlab = "", ylab = "")
```

## Iris example
```{r}
x <- iris[1:4]
y <- iris[5]
```

```{r}
results_iris_ica <- fastICA(x, n.comp = 2)
results_iris_ica
# TODO: Explain different matrices
```

```{r}
S <- data.frame(results_iris_ica$S)
S['class'] <- y

ggplot(S, aes(x = X1, y = X2, color = class)) + 
  geom_point()
```

# NMF

## Iris example
```{r}
x <- iris[1:4]
y <- iris[5]

results_iris_nmf <- nmf(x, rank = 2)
results_iris_nmf
```

```{r}
results_iris_nmf_H <- results_iris_nmf@fit@H
results_iris_nmf_H
```
```{r}
results_iris_nmf_W <- data.frame(results_iris_nmf@fit@W)
results_iris_nmf_W
```

```{r}
results_iris_nmf_W['y'] <- y

ggplot() +
  geom_point(data = results_iris_nmf_W, aes(x = X1, y = X2, color = y))
```

